apiVersion: v1
kind: Secret
metadata:
  name: sisko-secret
  namespace: sisko
type: Opaque
stringData:
  APP_KEY: "base64:CHANGE_ME"
  DB_USERNAME: "sisko"
  DB_PASSWORD: "CHANGE_ME"
  MIDTRANS_SERVER_KEY: ""
  MIDTRANS_CLIENT_KEY: ""
